name: deploy-container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: sync dist https://${{ secrets.BUCKET_NAME }}.s3-website.ir-thr-at1.arvanstorage.com

        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
